# Generated by Django 4.0.3 on 2022-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='CPF',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
