# Generated by Django 4.0.3 on 2022-05-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.CharField(choices=[('Babá', 'Babá'), ('Diarista', 'Diarista'), ('Encanador', 'Encanador')], max_length=50, null=True),
        ),
    ]
