# Generated by Django 4.0.3 on 2022-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfil_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('Trabalhador', 'Trabalhador'), ('Cliente', 'Cliente')], max_length=50, null=True),
        ),
    ]
