# Generated by Django 4.0.3 on 2022-06-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('perfil', '0011_remove_perfil_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Categoria', to='categoria.categoria'),
            preserve_default=False,
        ),
    ]
