# Generated by Django 4.0.3 on 2022-06-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_perfil_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
