# Generated by Django 4.0.3 on 2022-05-26 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('sobrenome', models.CharField(max_length=200, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('rua', models.CharField(max_length=300, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=300, null=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('tipo_usuario', models.CharField(choices=[('Trabalhador', 'Trabalhador'), ('Cliente', 'Cliente')], default='Cliente', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
