# Generated by Django 4.0.3 on 2022-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/imagens_perfil/'),
        ),
    ]
