# Generated by Django 4.0.3 on 2022-05-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0007_alter_perfil_tipo_usuario'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes_contrato', models.CharField(max_length=100, null=True)),
                ('data_serviço', models.DateField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('status_pagamento', models.CharField(choices=[('Aguardando', '1'), ('Realizado', '2')], default='1', max_length=50, null=True)),
                ('status_serviço', models.CharField(choices=[('Agendado', '1'), ('Em andamento', '2'), ('Realizado', '3')], default='1', max_length=50, null=True)),
                ('status_contrato', models.CharField(choices=[('Em aberto', '1'), ('Finalizado', '2'), ('Cancelado', '3')], default='1', max_length=50, null=True)),
                ('Avaliação_empregador', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Trabalhador', to='cliente.cliente')),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Trabalhador', to='perfil.perfil')),
            ],
        ),
    ]
