# Generated by Django 4.0.3 on 2022-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contrato_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Em aberto', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status_pagamento',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Realizado', 'Realizado')], default='Aguardando', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status_serviço',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Em andamento', 'Em andamento'), ('Realizado', 'Realizado')], default='Agendado', max_length=50, null=True),
        ),
    ]
