# Generated by Django 4.0.3 on 2022-06-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('contrato', '0004_alter_contrato_status_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cliente', to='cliente.cliente'),
        ),
    ]
