# Generated by Django 4.0.3 on 2022-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_alter_contrato_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Avaliação_empregador',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Avaliação_trabalhador',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='titulo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
