# Generated by Django 4.0.3 on 2022-06-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0008_alter_contrato_avaliação_trabalhador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_serviço',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_pagamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_serviço',
        ),
        migrations.AddField(
            model_name='contrato',
            name='avaliação_escrita',
            field=models.CharField(blank=True, max_length=500000),
        ),
    ]
