# Generated by Django 4.0.3 on 2022-06-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0009_remove_contrato_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=100, null=True),
        ),
    ]
