# Generated by Django 4.0.3 on 2022-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0010_contrato_status_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='Avaliação_trabalhador',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True),
        ),
    ]
