# Generated by Django 4.0.3 on 2022-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0011_alter_contrato_avaliação_trabalhador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='Avaliação_trabalhador',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
